const express = require('express');
const router = express.Router();

// Google Translate API integration
// Note: You'll need to install @google-cloud/translate and set up credentials
// For now, we'll use a simple translation service or mock implementation

// Mock translation function - replace with actual Google Translate API
const translateWithGoogle = async (text, targetLanguage, sourceLanguage = 'en') => {
  // This is a mock implementation
  // In production, you would use Google Translate API like this:
  /*
  const { Translate } = require('@google-cloud/translate').v2;
  const translate = new Translate({
    projectId: process.env.GOOGLE_CLOUD_PROJECT_ID,
    keyFilename: process.env.GOOGLE_CLOUD_KEY_FILE
  });

  try {
    const [translation] = await translate.translate(text, {
      from: sourceLanguage,
      to: targetLanguage
    });
    return translation;
  } catch (error) {
    console.error('Translation error:', error);
    return text;
  }
  */

  // Comprehensive mock translations for all supported languages
  const mockTranslations = {
    'te': {
      // Price Forecast Page
      'Price Trend': 'ధర ట్రెండ్',
      'Market Analysis': 'మార్కెట్ విశ్లేషణ',
      'Current Price': 'ప్రస్తుత ధర',
      '30-Day Forecast': '30-రోజుల అంచనా',
      'Confidence Level': 'విశ్వాస స్థాయి',
      'Time Range': 'సమయ పరిధి',
      'Year': 'సంవత్సరం',
      'Quick Filters': 'త్వరిత ఫిల్టర్లు',
      'This Week': 'ఈ వారం',
      'This Month': 'ఈ నెల',
      'This Quarter': 'ఈ త్రైమాసికం',
      'No Crops to Forecast': 'అంచనా వేయడానికి పంటలు లేవు',
      'Add crops in Account Centre to see price predictions': 'ధర అంచనాలను చూడటానికి ఖాతా కేంద్రంలో పంటలను జోడించండి',
      'per kg': 'కిలోకు',
      'Filters': 'ఫిల్టర్లు',
      'Advanced Filters': 'అధునాతన ఫిల్టర్లు',
      '7 Days': '7 రోజులు',
      '15 Days': '15 రోజులు',
      '30 Days': '30 రోజులు',
      '60 Days': '60 రోజులు',
      '90 Days': '90 రోజులు',
      
      // Updates Page
      'Updates': 'అప్‌డేట్‌లు',
      'Your notifications': 'మీ నోటిఫికేషన్‌లు',
      'No Updates Yet': 'ఇంకా అప్‌డేట్‌లు లేవు',
      'You\'ll see notifications here when there are updates': 'అప్‌డేట్‌లు ఉన్నప్పుడు మీరు వాటిని ఇక్కడ చూస్తారు',
      'Bid Completed - Winner Declared!': 'బిడ్ పూర్తయింది - విజేత ప్రకటించబడింది!',
      'Profile Changes Approved': 'ప్రొఫైల్ మార్పులు ఆమోదించబడ్డాయి',
      'New Connection Request': 'కొత్త కనెక్షన్ అభ్యర్థన',
      'Transport Update': 'రవాణా అప్‌డేట్',
      'Your bid for rice has ended! Winner': 'వరిపై మీ బిడ్ ముగిసింది! విజేత',
      'with': 'తో',
      'Contact': 'సంప్రదించండి',
      'Your profile change request has been approved! Updated fields': 'మీ ప్రొఫైల్ మార్పు అభ్యర్థన ఆమోదించబడింది! అప్‌డేట్ చేయబడిన ఫీల్డ్‌లు',
      'Land Size': 'భూమి పరిమాణం',
      'Your profile information has been updated successfully': 'మీ ప్రొఫైల్ సమాచారం విజయవంతంగా అప్‌డేట్ చేయబడింది',
      'NEW COM wants to connect with you. Check your connection requests to respond': 'NEW COM మీతో కనెక్ట్ అవ్వాలని అనుకుంటుంది. ప్రతిస్పందించడానికి మీ కనెక్షన్ అభ్యర్థనలను తనిఖీ చేయండి',
      'Driver on the way to pickup location. Tracking ID': 'డ్రైవర్ పికప్ లొకేషన్‌కు వెళ్తున్నాడు. ట్రాకింగ్ ID',
      
      // Weather Page - Comprehensive translations
      'Pest & Disease Risk': 'చీడపీడలు & వ్యాధి ప్రమాదం',
      'Fungal Disease Risk': 'ఫంగల్ వ్యాధి ప్రమాదం',
      'Apply fungicide if needed': 'అవసరమైతే ఫంగిసైడ్ వేయండి',
      'Monitor crops closely': 'పంటలను దగ్గరగా పర్యవేక్షించండి',
      'Conditions unfavorable for diseases': 'వ్యాధులకు అనుకూలం కాని పరిస్థితులు',
      'Pest Activity Level': 'చీడపీడల కార్యకలాప స్థాయి',
      'Normal pest activity expected': 'సాధారణ చీడపీడల కార్యకలాపాలు ఆశించబడుతున్నాయి',
      'Warm humid conditions favor pests': 'వెచ్చని తేమతో కూడిన పరిస్థితులు చీడపీడలకు అనుకూలం',
      'Cool conditions reduce pest activity': 'చల్లని పరిస్థితులు చీడపీడల కార్యకలాపాలను తగ్గిస్తాయి',
      'Moon & Astronomy': 'చంద్రుడు & ఖగోళ శాస్త్రం',
      'New Moon': 'అమావాస్య',
      'Moonrise': 'చంద్రోదయం',
      'Moonset': 'చంద్రాస్తమయం',
      'Dew Point': 'మంచు బిందువు',
      'Temperature Range': 'ఉష్ణోగ్రత పరిధి',
      'Auto-Refresh': 'ఆటో-రిఫ్రెష్',
      'Last': 'చివరిది',
      'Next refresh': 'తదుపరి రిఫ్రెష్',
      'High': 'అధిక',
      'Moderate': 'మధ్యస్థ',
      'Low': 'తక్కువ',
      'Current': 'ప్రస్తుత',
      'Min': 'కనిష్ట',
      'Max': 'గరిష్ట',
      'Live Weather Data': 'లైవ్ వాతావరణ డేటా',
      'Simulated Data': 'అనుకరణ డేటా',
      'Updated': 'అప్‌డేట్ చేయబడింది',
      'Hourly': 'గంటవారీ',
      'Five Day': '5-రోజు',
      'Now': 'ఇప్పుడు',
      'Today': 'ఈరోజు',
      'Wind': 'గాలి',
      'Humidity': 'తేమ',
      'Visibility': 'దృశ్యమానత',
      'Pressure': 'ఒత్తిడి',
      'Sunrise': 'సూర్యోదయం',
      'Sunset': 'సూర్యాస్తమయం',
      'Farming Advice': 'వ్యవసాయ సలహా',
      'Crop Conditions': 'పంట పరిస్థితులు',
      'Soil Moisture': 'మట్టి తేమ',
      'UV Index': 'UV సూచిక',
      'Feels Like': 'అనుభవం',
      'Rain Chance': 'వర్షం అవకాశం',
      'Best Times Today': 'ఈరోజు ఉత్తమ సమయాలు',
      'Irrigation': 'నీటిపారుదల',
      'Harvesting': 'పంట కోత',
      'Spraying': 'చల్లడం',
      'Field Work': 'పొలం పని',
      'Transplanting': 'మార్పిడి',
      'Not Recommended': 'సిఫార్సు చేయబడదు',
      'Ideal Conditions': 'అనువైన పరిస్థితులు',
      'Evening Preferred': 'సాయంత్రం ప్రాధాన్యత',
      'Air Quality Index': 'గాలి నాణ్యత సూచిక',
      'Overall AQI': 'మొత్తం AQI',
      'Good': 'మంచిది',
      'Unhealthy': 'అనారోగ్యకరమైన',
      'Very Unhealthy': 'చాలా అనారోగ్యకరమైన',
      'No Rain Expected': 'వర్షం అంచనా లేదు',
      'Rain Expected': 'వర్షం అంచనా',
      'Today\'s Agriculture Summary': 'ఈరోజు వ్యవసాయ సారాంశం',
      'Avg Temperature': 'సగటు ఉష్ణోగ్రత',
      'Max Wind': 'గరిష్ట గాలి',
      'Total Precipitation': 'మొత్తం వర్షపాతం',
      'Avg Humidity': 'సగటు తేమ',
      'Next 6 Hours (Live)': 'తదుపరి 6 గంటలు (లైవ్)',
      'Weather Alerts': 'వాతావరణ హెచ్చరికలు',
      'light breeze': 'తేలికపాటి గాలి',
      'clear': 'స్పష్టమైన',
      'hazy': 'మబ్బుగా',
      'normal': 'సాధారణ',
      'comfortable': 'సౌకర్యవంతమైన',
      'none': 'ఏదీ లేదు',
      'use protection': 'రక్షణ వాడండి',
      'very hot': 'చాలా వేడిమి',
      'warm': 'వెచ్చగా',
      'low probability': 'తక్కువ అవకాశం',
      'Moon Phase': 'చంద్ర దశ',
      'Moonrise': 'చంద్రోదయం',
      'Moonset': 'చంద్రాస్తమయం',
      'Dew Point': 'మంచు బిందువు',
      
      // Additional weather terms
      'sunny': 'ఎండగా',
      'cloudy': 'మేఘావృతం',
      'rainy': 'వర్షం',
      'clear': 'స్పష్టమైన',
      'overcast': 'మేఘాలతో కప్పబడిన',
      'mist': 'పొగమంచు',
      'fog': 'మంచు',
      'drizzle': 'చినుకులు',
      'storm': 'తుఫాను',
      'partly cloudy': 'పాక్షిక మేఘావృతం',
      
      // Farming advice terms
      'high heat irrigate early morning': 'అధిక వేడిమిలో ఉదయం పూట నీరు పోయండి',
      'cool weather protect from frost': 'చల్లని వాతావరణంలో మంచు నుండి రక్షించండి',
      'good temperature for farming': 'వ్యవసాయానికి మంచి ఉష్ణోగ్రత',
      'rain expected avoid spraying': 'వర్షం అంచనా - స్ప్రే చేయవద్దు',
      'good time for transplanting': 'మార్పిడికి మంచి సమయం',
      'high humidity watch fungal': 'అధిక తేమ - ఫంగల్ వ్యాధులను గమనించండి',
      'clear skies ideal for harvesting': 'స్పష్టమైన ఆకాశం - కోతకు అనువైనది',
      
      // Crop names
      'Rice': 'వరి',
      'Wheat': 'గోధుమ',
      'Coffee': 'కాఫీ',
      'Corn': 'మొక్కజొన్న',
      'Cotton': 'పత్తి',
      'Sugarcane': 'చెరకు',
      'Tomato': 'టమాటో',
      'Onion': 'ఉల్లిపాయ',
      'Potato': 'బంగాళాదుంప',
      'Chili': 'మిర్చి',
      
      // Dashboard and UI elements
      'Leaderboard': 'లీడర్‌బోర్డ్',
      'Top performers': 'అగ్రగామి వ్యక్తులు',
      'No sales data yet': 'ఇంకా అమ్మకాల డేటా లేదు',
      'Track your crops': 'మీ పంటలను ట్రాక్ చేయండి',
      'Unable to fetch live data for rice. Showing estimated prices based on typical market rates.': 'వరికి లైవ్ డేటాను పొందలేకపోయాము. సాధారణ మార్కెట్ రేట్ల ఆధారంగా అంచనా ధరలను చూపిస్తున్నాము.',
      'Unable to fetch live data': 'లైవ్ డేటాను పొందలేకపోయాము',
      'Showing estimated prices based on typical market rates': 'సాధారణ మార్కెట్ రేట్ల ఆధారంగా అంచనా ధరలను చూపిస్తున్నాము',
      
      // Weather conditions
      'Mist': 'పొగమంచు',
      'Fog': 'మంచు',
      'Haze': 'పొగమంచు',
      'Drizzle': 'చినుకులు',
      'Showers': 'వర్షం',
      'Thunderstorm': 'ఉరుములతో కూడిన వర్షం',
      'Snow': 'మంచు',
      'Sleet': 'మంచు వర్షం',
      'Partly Cloudy': 'పాక్షిక మేఘావృతం',
      'Mostly Cloudy': 'ఎక్కువగా మేఘావృతం',
      'Overcast': 'పూర్తిగా మేఘావృతం',
      'Clear Sky': 'స్పష్టమైన ఆకాశం',
      'Fair': 'మంచి వాతావరణం',
      
      // Common words that appear frequently
      'Home': 'హోమ్',
      'Back': 'వెనుకకు',
      'Loading...': 'లోడ్ అవుతోంది...',
      'Error': 'లోపం',
      'Success': 'విజయం',
      'Warning': 'హెచ్చరిక',
      'Information': 'సమాచారం',
      'Close': 'మూసివేయండి',
      'Save': 'సేవ్ చేయండి',
      'Cancel': 'రద్దు చేయండి',
      'Submit': 'సమర్పించండి',
      'Delete': 'తొలగించండి',
      'Edit': 'సవరించండి',
      'View': 'చూడండి',
      'Search': 'శోధించండి',
      'Filter': 'ఫిల్టర్',
      'Refresh': 'రిఫ్రెష్ చేయండి',
      'Try Again': 'మళ్లీ ప్రయత్నించండి',
      'Retry': 'మళ్లీ ప్రయత్నించండి',
      'No data available': 'డేటా అందుబాటులో లేదు',
      'Failed to load': 'లోడ్ చేయడంలో విఫలమైంది',
      'Please try again': 'దయచేసి మళ్లీ ప్రయత్నించండి',
      'An error occurred': 'లోపం సంభవించింది',
      'Loading': 'లోడ్ అవుతోంది',
      'Updating': 'అప్‌డేట్ అవుతోంది'
    },
    'hi': {
      // Price Forecast Page
      'Price Trend': 'मूल्य रुझान',
      'Market Analysis': 'बाजार विश्लेषण',
      'Current Price': 'वर्तमान मूल्य',
      '30-Day Forecast': '30-दिन पूर्वानुमान',
      'Confidence Level': 'विश्वास स्तर',
      'Time Range': 'समय सीमा',
      'Year': 'वर्ष',
      'Quick Filters': 'त्वरित फिल्टर',
      'This Week': 'इस सप्ताह',
      'This Month': 'इस महीने',
      'This Quarter': 'इस तिमाही',
      'No Crops to Forecast': 'पूर्वानुमान के लिए कोई फसल नहीं',
      'Add crops in Account Centre to see price predictions': 'मूल्य पूर्वानुमान देखने के लिए खाता केंद्र में फसलें जोड़ें',
      'per kg': 'प्रति किलो',
      'Filters': 'फिल्टर',
      'Advanced Filters': 'उन्नत फिल्टर',
      '7 Days': '7 दिन',
      '15 Days': '15 दिन',
      '30 Days': '30 दिन',
      '60 Days': '60 दिन',
      '90 Days': '90 दिन',
      
      // Updates Page
      'Updates': 'अपडेट',
      'Your notifications': 'आपकी सूचनाएं',
      'No Updates Yet': 'अभी तक कोई अपडेट नहीं',
      'You\'ll see notifications here when there are updates': 'अपडेट होने पर आप यहां सूचनाएं देखेंगे',
      'Bid Completed - Winner Declared!': 'बोली पूर्ण - विजेता घोषित!',
      'Profile Changes Approved': 'प्रोफाइल परिवर्तन स्वीकृत',
      'New Connection Request': 'नया कनेक्शन अनुरोध',
      'Transport Update': 'परिवहन अपडेट',
      
      // Weather Page - Comprehensive translations
      'Pest & Disease Risk': 'कीट और रोग जोखिम',
      'Fungal Disease Risk': 'फंगल रोग जोखिम',
      'Apply fungicide if needed': 'आवश्यकता पड़ने पर फफूंदनाशी लगाएं',
      'Monitor crops closely': 'फसलों की बारीकी से निगरानी करें',
      'Conditions unfavorable for diseases': 'रोगों के लिए प्रतिकूल परिस्थितियां',
      'Pest Activity Level': 'कीट गतिविधि स्तर',
      'Normal pest activity expected': 'सामान्य कीट गतिविधि अपेक्षित',
      'Warm humid conditions favor pests': 'गर्म आर्द्र परिस्थितियां कीटों के अनुकूल',
      'Cool conditions reduce pest activity': 'ठंडी परिस्थितियां कीट गतिविधि कम करती हैं',
      'Moon & Astronomy': 'चांद और खगोल विज्ञान',
      'New Moon': 'नया चांद',
      'Moonrise': 'चांद उगना',
      'Moonset': 'चांद डूबना',
      'Dew Point': 'ओस बिंदु',
      'Temperature Range': 'तापमान सीमा',
      'Auto-Refresh': 'ऑटो-रिफ्रेश',
      'Last': 'अंतिम',
      'Next refresh': 'अगला रिफ्रेश',
      'High': 'उच्च',
      'Moderate': 'मध्यम',
      'Low': 'कम',
      'Current': 'वर्तमान',
      'Min': 'न्यूनतम',
      'Max': 'अधिकतम',
      'Live Weather Data': 'लाइव मौसम डेटा',
      'Simulated Data': 'सिमुलेटेड डेटा',
      'Updated': 'अपडेट किया गया',
      'Hourly': 'प्रति घंटा',
      'Five Day': '5-दिन',
      'Now': 'अब',
      'Today': 'आज',
      'Wind': 'हवा',
      'Humidity': 'आर्द्रता',
      'Visibility': 'दृश्यता',
      'Pressure': 'दबाव',
      'Sunrise': 'सूर्योदय',
      'Sunset': 'सूर्यास्त',
      'Farming Advice': 'कृषि सलाह',
      'Crop Conditions': 'फसल की स्थिति',
      'Soil Moisture': 'मिट्टी की नमी',
      'UV Index': 'UV सूचकांक',
      'Feels Like': 'महसूस होता है',
      'Rain Chance': 'बारिश की संभावना',
      'Best Times Today': 'आज के सर्वोत्तम समय',
      'Irrigation': 'सिंचाई',
      'Harvesting': 'कटाई',
      'Spraying': 'छिड़काव',
      'Field Work': 'खेत का काम',
      'Transplanting': 'प्रत्यारोपण',
      'Not Recommended': 'अनुशंसित नहीं',
      'Ideal Conditions': 'आदर्श परिस्थितियां',
      'Evening Preferred': 'शाम को प्राथमिकता',
      'Air Quality Index': 'वायु गुणवत्ता सूचकांक',
      'Overall AQI': 'समग्र AQI',
      'Good': 'अच्छा',
      'Unhealthy': 'अस्वस्थ',
      'Very Unhealthy': 'बहुत अस्वस्थ',
      'No Rain Expected': 'बारिश की उम्मीद नहीं',
      'Rain Expected': 'बारिश की उम्मीद',
      'Today\'s Agriculture Summary': 'आज का कृषि सारांश',
      'Avg Temperature': 'औसत तापमान',
      'Max Wind': 'अधिकतम हवा',
      'Total Precipitation': 'कुल वर्षा',
      'Avg Humidity': 'औसत आर्द्रता',
      'Next 6 Hours (Live)': 'अगले 6 घंटे (लाइव)',
      'Weather Alerts': 'मौसम चेतावनी',
      
      // Crop names
      'Rice': 'चावल',
      'Wheat': 'गेहूं',
      'Coffee': 'कॉफी',
      'Corn': 'मक्का',
      'Cotton': 'कपास',
      'Sugarcane': 'गन्ना',
      'Tomato': 'टमाटर',
      'Onion': 'प्याज',
      'Potato': 'आलू',
      'Chili': 'मिर्च',
      
      // Dashboard and UI elements
      'Leaderboard': 'लीडरबोर्ड',
      'Top performers': 'शीर्ष प्रदर्शनकर्ता',
      'No sales data yet': 'अभी तक कोई बिक्री डेटा नहीं',
      'Track your crops': 'अपनी फसलों को ट्रैक करें',
      'Unable to fetch live data for rice. Showing estimated prices based on typical market rates.': 'चावल के लिए लाइव डेटा प्राप्त करने में असमर्थ। सामान्य बाजार दरों के आधार पर अनुमानित कीमतें दिखा रहे हैं।',
      'Unable to fetch live data': 'लाइव डेटा प्राप्त करने में असमर्थ',
      'Showing estimated prices based on typical market rates': 'सामान्य बाजार दरों के आधार पर अनुमानित कीमतें दिखा रहे हैं',
      
      // Weather conditions
      'Mist': 'धुंध',
      'Fog': 'कोहरा',
      'Haze': 'धुंध',
      'Drizzle': 'बूंदाबांदी',
      'Showers': 'बारिश',
      'Thunderstorm': 'तूफान',
      'Snow': 'बर्फ',
      'Sleet': 'बर्फीली बारिश',
      'Partly Cloudy': 'आंशिक रूप से बादल',
      'Mostly Cloudy': 'ज्यादातर बादल',
      'Overcast': 'पूरी तरह बादल',
      'Clear Sky': 'साफ आसमान',
      'Fair': 'अच्छा मौसम',
      
      // Common words
      'Home': 'होम',
      'Back': 'वापस',
      'Loading...': 'लोड हो रहा है...',
      'Error': 'त्रुटि',
      'Success': 'सफलता',
      'Warning': 'चेतावनी',
      'Information': 'जानकारी',
      'Close': 'बंद करें',
      'Save': 'सेव करें',
      'Cancel': 'रद्द करें',
      'Submit': 'जमा करें',
      'Delete': 'हटाएं',
      'Edit': 'संपादित करें',
      'View': 'देखें',
      'Search': 'खोजें',
      'Filter': 'फिल्टर',
      'Refresh': 'रिफ्रेश करें',
      'Try Again': 'फिर कोशिश करें',
      'Retry': 'पुनः प्रयास',
      'No data available': 'कोई डेटा उपलब्ध नहीं',
      'Failed to load': 'लोड करने में विफल',
      'Please try again': 'कृपया पुनः प्रयास करें',
      'An error occurred': 'एक त्रुटि हुई',
      'Loading': 'लोड हो रहा है',
      'Updating': 'अपडेट हो रहा है'
    },
    'hi': {
      'Price Trend': 'मूल्य रुझान',
      'Market Analysis': 'बाजार विश्लेषण',
      'Current Price': 'वर्तमान मूल्य',
      '30-Day Forecast': '30-दिन पूर्वानुमान',
      'Confidence Level': 'विश्वास स्तर',
      'Time Range': 'समय सीमा',
      'Year': 'वर्ष',
      'Quick Filters': 'त्वरित फिल्टर',
      'This Week': 'इस सप्ताह',
      'This Month': 'इस महीने',
      'This Quarter': 'इस तिमाही',
      'No Crops to Forecast': 'पूर्वानुमान के लिए कोई फसल नहीं',
      'Add crops in Account Centre to see price predictions': 'मूल्य पूर्वानुमान देखने के लिए खाता केंद्र में फसलें जोड़ें',
      'per kg': 'प्रति किलो',
      'Filters': 'फिल्टर',
      'Advanced Filters': 'उन्नत फिल्टर',
      '7 Days': '7 दिन',
      '15 Days': '15 दिन',
      '30 Days': '30 दिन',
      '60 Days': '60 दिन',
      '90 Days': '90 दिन',
      // Updates Page
      'Updates': 'अपडेट',
      'Your notifications': 'आपकी सूचनाएं',
      'No Updates Yet': 'अभी तक कोई अपडेट नहीं',
      'Bid Completed - Winner Declared!': 'बोली पूर्ण - विजेता घोषित!',
      'Profile Changes Approved': 'प्रोफाइल परिवर्तन स्वीकृत',
      'New Connection Request': 'नया कनेक्शन अनुरोध',
      'Transport Update': 'परिवहन अपडेट',
      // Weather Page
      'Pest & Disease Risk': 'कीट और रोग जोखिम',
      'Fungal Disease Risk': 'फंगल रोग जोखिम',
      'Apply fungicide if needed': 'आवश्यकता पड़ने पर फफूंदनाशी लगाएं',
      'Pest Activity Level': 'कीट गतिविधि स्तर',
      'Normal pest activity expected': 'सामान्य कीट गतिविधि अपेक्षित',
      'Moon & Astronomy': 'चांद और खगोल विज्ञान',
      'New Moon': 'नया चांद',
      'Moonrise': 'चांद उगना',
      'Moonset': 'चांद डूबना',
      'Dew Point': 'ओस बिंदु',
      'Temperature Range': 'तापमान सीमा',
      'Auto-Refresh': 'ऑटो-रिफ्रेश',
      'Last': 'अंतिम',
      'Next refresh': 'अगला रिफ्रेश',
      'High': 'उच्च',
      'Moderate': 'मध्यम',
      'Low': 'कम',
      'Current': 'वर्तमान',
      'Min': 'न्यूनतम',
      'Max': 'अधिकतम'
    },
    'ta': {
      // Price Forecast Page
      'Price Trend': 'விலை போக்கு',
      'Market Analysis': 'சந்தை பகுப்பாய்வு',
      'Current Price': 'தற்போதைய விலை',
      '30-Day Forecast': '30-நாள் முன்னறிவிப்பு',
      'Confidence Level': 'நம்பிக்கை நிலை',
      'Time Range': 'நேர வரம்பு',
      'Year': 'ஆண்டு',
      'Quick Filters': 'விரைவு வடிகட்டிகள்',
      'This Week': 'இந்த வாரம்',
      'This Month': 'இந்த மாதம்',
      'This Quarter': 'இந்த காலாண்டு',
      'No Crops to Forecast': 'முன்னறிவிப்பிற்கு பயிர்கள் இல்லை',
      'Add crops in Account Centre to see price predictions': 'விலை முன்னறிவிப்புகளைப் பார்க்க கணக்கு மையத்தில் பயிர்களைச் சேர்க்கவும்',
      'per kg': 'கிலோவிற்கு',
      'Filters': 'வடிகட்டிகள்',
      'Advanced Filters': 'மேம்பட்ட வடிகட்டிகள்',
      '7 Days': '7 நாட்கள்',
      '15 Days': '15 நாட்கள்',
      '30 Days': '30 நாட்கள்',
      '60 Days': '60 நாட்கள்',
      '90 Days': '90 நாட்கள்',
      
      // Updates Page
      'Updates': 'புதுப்பிப்புகள்',
      'Your notifications': 'உங்கள் அறிவிப்புகள்',
      'No Updates Yet': 'இன்னும் புதுப்பிப்புகள் இல்லை',
      'You\'ll see notifications here when there are updates': 'புதுப்பிப்புகள் இருக்கும்போது நீங்கள் இங்கே அறிவிப்புகளைக் காண்பீர்கள்',
      'Bid Completed - Winner Declared!': 'ஏலம் முடிந்தது - வெற்றியாளர் அறிவிக்கப்பட்டார்!',
      'Profile Changes Approved': 'சுயவிவர மாற்றங்கள் அங்கீகரிக்கப்பட்டன',
      'New Connection Request': 'புதிய இணைப்பு கோரிக்கை',
      'Transport Update': 'போக்குவரத்து புதுப்பிப்பு',
      
      // Weather Page - Comprehensive translations
      'Pest & Disease Risk': 'பூச்சி மற்றும் நோய் ஆபத்து',
      'Fungal Disease Risk': 'பூஞ்சை நோய் ஆபத்து',
      'Apply fungicide if needed': 'தேவைப்பட்டால் பூஞ்சைக் கொல்லி பயன்படுத்தவும்',
      'Monitor crops closely': 'பயிர்களை நெருக்கமாக கண்காணிக்கவும்',
      'Conditions unfavorable for diseases': 'நோய்களுக்கு சாதகமற்ற நிலைமைகள்',
      'Pest Activity Level': 'பூச்சி செயல்பாட்டு நிலை',
      'Normal pest activity expected': 'சாதாரண பூச்சி செயல்பாடு எதிர்பார்க்கப்படுகிறது',
      'Warm humid conditions favor pests': 'வெப்பமான ஈரப்பதமான நிலைமைகள் பூச்சிகளுக்கு சாதகம்',
      'Cool conditions reduce pest activity': 'குளிர்ந்த நிலைமைகள் பூச்சி செயல்பாட்டைக் குறைக்கின்றன',
      'Moon & Astronomy': 'சந்திரன் மற்றும் வானியல்',
      'New Moon': 'அமாவாசை',
      'Moonrise': 'சந்திர உதயம்',
      'Moonset': 'சந்திர அஸ்தமனம்',
      'Dew Point': 'பனி புள்ளி',
      'Temperature Range': 'வெப்பநிலை வரம்பு',
      'Auto-Refresh': 'தானியங்கி புதுப்பிப்பு',
      'Last': 'கடைசி',
      'Next refresh': 'அடுத்த புதுப்பிப்பு',
      'High': 'அதிக',
      'Moderate': 'மிதமான',
      'Low': 'குறைவான',
      'Current': 'தற்போதைய',
      'Min': 'குறைந்தபட்சம்',
      'Max': 'அதிகபட்சம்',
      'Live Weather Data': 'நேரடி வானிலை தரவு',
      'Simulated Data': 'உருவகப்படுத்தப்பட்ட தரவு',
      'Updated': 'புதுப்பிக்கப்பட்டது',
      'Hourly': 'மணிநேர',
      'Five Day': '5-நாள்',
      'Now': 'இப்போது',
      'Today': 'இன்று',
      'Wind': 'காற்று',
      'Humidity': 'ஈரப்பதம்',
      'Visibility': 'தெரிவுநிலை',
      'Pressure': 'அழுத்தம்',
      'Sunrise': 'சூரிய உதயம்',
      'Sunset': 'சூரிய அஸ்தமனம்',
      'Farming Advice': 'விவசாய ஆலோசனை',
      'Crop Conditions': 'பயிர் நிலைமைகள்',
      'Soil Moisture': 'மண் ஈரப்பதம்',
      'UV Index': 'UV குறியீடு',
      'Feels Like': 'உணர்வு',
      'Rain Chance': 'மழை வாய்ப்பு',
      'Best Times Today': 'இன்றைய சிறந்த நேரங்கள்',
      'Irrigation': 'நீர்ப்பாசனம்',
      'Harvesting': 'அறுவடை',
      'Spraying': 'தெளித்தல்',
      'Field Work': 'வயல் வேலை',
      'Transplanting': 'நடவு',
      'Not Recommended': 'பரிந்துரைக்கப்படவில்லை',
      'Ideal Conditions': 'சிறந்த நிலைமைகள்',
      'Evening Preferred': 'மாலை விரும்பத்தக்கது',
      'Air Quality Index': 'காற்று தர குறியீடு',
      'Overall AQI': 'ஒட்டுமொத்த AQI',
      'Good': 'நல்லது',
      'Unhealthy': 'ஆரோக்கியமற்றது',
      'Very Unhealthy': 'மிகவும் ஆரோக்கியமற்றது',
      'No Rain Expected': 'மழை எதிர்பார்க்கப்படவில்லை',
      'Rain Expected': 'மழை எதிர்பார்க்கப்படுகிறது',
      'Today\'s Agriculture Summary': 'இன்றைய விவசாய சுருக்கம்',
      'Avg Temperature': 'சராசரி வெப்பநிலை',
      'Max Wind': 'அதிகபட்ச காற்று',
      'Total Precipitation': 'மொத்த மழைப்பொழிவு',
      'Avg Humidity': 'சராசரி ஈரப்பதம்',
      'Next 6 Hours (Live)': 'அடுத்த 6 மணிநேரம் (நேரடி)',
      'Weather Alerts': 'வானிலை எச்சரிக்கைகள்',
      
      // Crop names
      'Rice': 'அரிசி',
      'Wheat': 'கோதுமை',
      'Coffee': 'காபி',
      'Corn': 'சோளம்',
      'Cotton': 'பருத்தி',
      'Sugarcane': 'கரும்பு',
      'Tomato': 'தக்காளி',
      'Onion': 'வெங்காயம்',
      'Potato': 'உருளைக்கிழங்கு',
      'Chili': 'மிளகாய்',
      
      // Dashboard and UI elements
      'Leaderboard': 'தலைமை பலகை',
      'Top performers': 'சிறந்த செயல்பாட்டாளர்கள்',
      'No sales data yet': 'இன்னும் விற்பனை தரவு இல்லை',
      'Track your crops': 'உங்கள் பயிர்களைக் கண்காணிக்கவும்',
      'Unable to fetch live data for rice. Showing estimated prices based on typical market rates.': 'அரிசிக்கான நேரடி தரவைப் பெற முடியவில்லை. வழக்கமான சந்தை விலைகளின் அடிப்படையில் மதிப்பிடப்பட்ட விலைகளைக் காட்டுகிறது.',
      'Unable to fetch live data': 'நேரடி தரவைப் பெற முடியவில்லை',
      'Showing estimated prices based on typical market rates': 'வழக்கமான சந்தை விலைகளின் அடிப்படையில் மதிப்பிடப்பட்ட விலைகளைக் காட்டுகிறது',
      
      // Weather conditions
      'Mist': 'மூடுபனி',
      'Fog': 'பனி',
      'Haze': 'மூடுபனி',
      'Drizzle': 'தூறல்',
      'Showers': 'மழை',
      'Thunderstorm': 'இடியுடன் கூடிய மழை',
      'Snow': 'பனி',
      'Sleet': 'பனி மழை',
      'Partly Cloudy': 'பகுதியளவு மேகமூட்டம்',
      'Mostly Cloudy': 'பெரும்பாலும் மேகமூட்டம்',
      'Overcast': 'முழுவதும் மேகமூட்டம்',
      'Clear Sky': 'தெளிவான வானம்',
      'Fair': 'நல்ல வானிலை',
      
      // Common words
      'Home': 'முகப்பு',
      'Back': 'பின்',
      'Loading...': 'ஏற்றுகிறது...',
      'Error': 'பிழை',
      'Success': 'வெற்றி',
      'Warning': 'எச்சரிக்கை',
      'Information': 'தகவல்',
      'Close': 'மூடு',
      'Save': 'சேமி',
      'Cancel': 'ரத்து',
      'Submit': 'சமர்ப்பி',
      'Delete': 'நீக்கு',
      'Edit': 'திருத்து',
      'View': 'பார்',
      'Search': 'தேடு',
      'Filter': 'வடிகட்டி',
      'Refresh': 'புதுப்பி',
      'Try Again': 'மீண்டும் முயற்சி',
      'Retry': 'மீண்டும் முயற்சி',
      'No data available': 'தரவு கிடைக்கவில்லை',
      'Failed to load': 'ஏற்றுவதில் தோல்வி',
      'Please try again': 'தயவுசெய்து மீண்டும் முயற்சிக்கவும்',
      'An error occurred': 'ஒரு பிழை ஏற்பட்டது',
      'Loading': 'ஏற்றுகிறது',
      'Updating': 'புதுப்பிக்கிறது'
    },
    'ml': {
      // Price Forecast Page
      'Price Trend': 'വില ട്രെൻഡ്',
      'Market Analysis': 'മാർക്കറ്റ് വിശകലനം',
      'Current Price': 'നിലവിലെ വില',
      '30-Day Forecast': '30-ദിവസ പ്രവചനം',
      'Confidence Level': 'വിശ്വാസ നില',
      'Time Range': 'സമയ പരിധി',
      'Year': 'വർഷം',
      'Quick Filters': 'ദ്രുത ഫിൽട്ടറുകൾ',
      'This Week': 'ഈ ആഴ്ച',
      'This Month': 'ഈ മാസം',
      'This Quarter': 'ഈ ത്രൈമാസികം',
      'No Crops to Forecast': 'പ്രവചിക്കാൻ വിളകളില്ല',
      'Add crops in Account Centre to see price predictions': 'വില പ്രവചനങ്ങൾ കാണാൻ അക്കൗണ്ട് സെന്ററിൽ വിളകൾ ചേർക്കുക',
      'per kg': 'കിലോയ്ക്ക്',
      'Filters': 'ഫിൽട്ടറുകൾ',
      'Advanced Filters': 'വിപുലമായ ഫിൽട്ടറുകൾ',
      '7 Days': '7 ദിവസം',
      '15 Days': '15 ദിവസം',
      '30 Days': '30 ദിവസം',
      '60 Days': '60 ദിവസം',
      '90 Days': '90 ദിവസം',
      
      // Updates Page
      'Updates': 'അപ്ഡേറ്റുകൾ',
      'Your notifications': 'നിങ്ങളുടെ അറിയിപ്പുകൾ',
      'No Updates Yet': 'ഇതുവരെ അപ്ഡേറ്റുകളില്ല',
      'You\'ll see notifications here when there are updates': 'അപ്ഡേറ്റുകൾ ഉണ്ടാകുമ്പോൾ നിങ്ങൾ ഇവിടെ അറിയിപ്പുകൾ കാണും',
      'Bid Completed - Winner Declared!': 'ലേലം പൂർത്തിയായി - വിജയി പ്രഖ്യാപിച്ചു!',
      'Profile Changes Approved': 'പ്രൊഫൈൽ മാറ്റങ്ങൾ അംഗീകരിച്ചു',
      'New Connection Request': 'പുതിയ കണക്ഷൻ അഭ്യർത്ഥന',
      'Transport Update': 'ഗതാഗത അപ്ഡേറ്റ്',
      
      // Weather Page - Comprehensive translations
      'Pest & Disease Risk': 'കീടങ്ങളും രോഗങ്ങളും അപകടസാധ്യത',
      'Fungal Disease Risk': 'ഫംഗൽ രോഗ അപകടസാധ്യത',
      'Apply fungicide if needed': 'ആവശ്യമെങ്കിൽ ഫംഗിസൈഡ് പ്രയോഗിക്കുക',
      'Monitor crops closely': 'വിളകൾ സൂക്ഷ്മമായി നിരീക്ഷിക്കുക',
      'Conditions unfavorable for diseases': 'രോഗങ്ങൾക്ക് പ്രതികൂലമായ അവസ്ഥകൾ',
      'Pest Activity Level': 'കീട പ്രവർത്തന നില',
      'Normal pest activity expected': 'സാധാരണ കീട പ്രവർത്തനം പ്രതീക്ഷിക്കുന്നു',
      'Warm humid conditions favor pests': 'ചൂടുള്ള ഈർപ്പമുള്ള അവസ്ഥകൾ കീടങ്ങൾക്ക് അനുകൂലം',
      'Cool conditions reduce pest activity': 'തണുത്ത അവസ്ഥകൾ കീട പ്രവർത്തനം കുറയ്ക്കുന്നു',
      'Moon & Astronomy': 'ചന്ദ്രനും ജ്യോതിശാസ്ത്രവും',
      'New Moon': 'അമാവാസി',
      'Moonrise': 'ചന്ദ്രോദയം',
      'Moonset': 'ചന്ദ്രാസ്തമയം',
      'Dew Point': 'മഞ്ഞു പോയിന്റ്',
      'Temperature Range': 'താപനില പരിധി',
      'Auto-Refresh': 'ഓട്ടോ-റിഫ്രഷ്',
      'Last': 'അവസാനം',
      'Next refresh': 'അടുത്ത റിഫ്രഷ്',
      'High': 'ഉയർന്ന',
      'Moderate': 'മിതമായ',
      'Low': 'കുറഞ്ഞ',
      'Current': 'നിലവിലെ',
      'Min': 'കുറഞ്ഞത്',
      'Max': 'കൂടിയത്',
      'Live Weather Data': 'തത്സമയ കാലാവസ്ഥാ ഡാറ്റ',
      'Simulated Data': 'സിമുലേറ്റഡ് ഡാറ്റ',
      'Updated': 'അപ്ഡേറ്റ് ചെയ്തു',
      'Hourly': 'മണിക്കൂറിൽ',
      'Five Day': '5-ദിവസം',
      'Now': 'ഇപ്പോൾ',
      'Today': 'ഇന്ന്',
      'Wind': 'കാറ്റ്',
      'Humidity': 'ഈർപ്പം',
      'Visibility': 'ദൃശ്യത',
      'Pressure': 'മർദ്ദം',
      'Sunrise': 'സൂര്യോദയം',
      'Sunset': 'സൂര്യാസ്തമയം',
      'Farming Advice': 'കൃഷി ഉപദേശം',
      'Crop Conditions': 'വിള അവസ്ഥകൾ',
      'Soil Moisture': 'മണ്ണിന്റെ ഈർപ്പം',
      'UV Index': 'UV സൂചിക',
      'Feels Like': 'അനുഭവപ്പെടുന്നത്',
      'Rain Chance': 'മഴയുടെ സാധ്യത',
      'Best Times Today': 'ഇന്നത്തെ മികച്ച സമയങ്ങൾ',
      'Irrigation': 'ജലസേചനം',
      'Harvesting': 'വിളവെടുപ്പ്',
      'Spraying': 'സ്പ്രേയിംഗ്',
      'Field Work': 'വയൽ ജോലി',
      'Transplanting': 'നടീൽ',
      'Not Recommended': 'ശുപാർശ ചെയ്യുന്നില്ല',
      'Ideal Conditions': 'അനുയോജ്യമായ അവസ്ഥകൾ',
      'Evening Preferred': 'വൈകുന്നേരം മുൻഗണന',
      'Air Quality Index': 'വായു ഗുണനിലവാര സൂചിക',
      'Overall AQI': 'മൊത്തത്തിലുള്ള AQI',
      'Good': 'നല്ലത്',
      'Unhealthy': 'അനാരോഗ്യകരം',
      'Very Unhealthy': 'വളരെ അനാരോഗ്യകരം',
      'No Rain Expected': 'മഴ പ്രതീക്ഷിക്കുന്നില്ല',
      'Rain Expected': 'മഴ പ്രതീക്ഷിക്കുന്നു',
      'Today\'s Agriculture Summary': 'ഇന്നത്തെ കൃഷി സംഗ്രഹം',
      'Avg Temperature': 'ശരാശരി താപനില',
      'Max Wind': 'പരമാവധി കാറ്റ്',
      'Total Precipitation': 'മൊത്തം മഴ',
      'Avg Humidity': 'ശരാശരി ഈർപ്പം',
      'Next 6 Hours (Live)': 'അടുത്ത 6 മണിക്കൂർ (തത്സമയം)',
      'Weather Alerts': 'കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ',
      
      // Crop names
      'Rice': 'അരി',
      'Wheat': 'ഗോതമ്പ്',
      'Coffee': 'കാപ്പി',
      'Corn': 'ചോളം',
      'Cotton': 'പരുത്തി',
      'Sugarcane': 'കരിമ്പ്',
      'Tomato': 'തക്കാളി',
      'Onion': 'ഉള്ളി',
      'Potato': 'ഉരുളക്കിഴങ്ങ്',
      'Chili': 'മുളക്',
      
      // Dashboard and UI elements
      'Leaderboard': 'ലീഡർബോർഡ്',
      'Top performers': 'മികച്ച പ്രകടനം കാഴ്ചവെക്കുന്നവർ',
      'No sales data yet': 'ഇതുവരെ വിൽപ്പന ഡാറ്റയില്ല',
      'Track your crops': 'നിങ്ങളുടെ വിളകൾ ട്രാക്ക് ചെയ്യുക',
      'Unable to fetch live data for rice. Showing estimated prices based on typical market rates.': 'അരിക്കുള്ള തത്സമയ ഡാറ്റ ലഭിക്കാൻ കഴിയുന്നില്ല. സാധാരണ മാർക്കറ്റ് നിരക്കുകളുടെ അടിസ്ഥാനത്തിൽ കണക്കാക്കിയ വിലകൾ കാണിക്കുന്നു.',
      'Unable to fetch live data': 'തത്സമയ ഡാറ്റ ലഭിക്കാൻ കഴിയുന്നില്ല',
      'Showing estimated prices based on typical market rates': 'സാധാരണ മാർക്കറ്റ് നിരക്കുകളുടെ അടിസ്ഥാനത്തിൽ കണക്കാക്കിയ വിലകൾ കാണിക്കുന്നു',
      
      // Weather conditions
      'Mist': 'മൂടൽമഞ്ഞ്',
      'Fog': 'മഞ്ഞ്',
      'Haze': 'മൂടൽമഞ്ഞ്',
      'Drizzle': 'ചാറ്റൽമഴ',
      'Showers': 'മഴ',
      'Thunderstorm': 'ഇടിമിന്നലോടുകൂടിയ മഴ',
      'Snow': 'മഞ്ഞ്',
      'Sleet': 'മഞ്ഞ് മഴ',
      'Partly Cloudy': 'ഭാഗികമായി മേഘാവൃതം',
      'Mostly Cloudy': 'കൂടുതലും മേഘാവൃതം',
      'Overcast': 'പൂർണ്ണമായും മേഘാവൃതം',
      'Clear Sky': 'തെളിഞ്ഞ ആകാശം',
      'Fair': 'നല്ല കാലാവസ്ഥ',
      
      // Common words
      'Home': 'ഹോം',
      'Back': 'തിരികെ',
      'Loading...': 'ലോഡ് ചെയ്യുന്നു...',
      'Error': 'പിശക്',
      'Success': 'വിജയം',
      'Warning': 'മുന്നറിയിപ്പ്',
      'Information': 'വിവരങ്ങൾ',
      'Close': 'അടയ്ക്കുക',
      'Save': 'സേവ് ചെയ്യുക',
      'Cancel': 'റദ്ദാക്കുക',
      'Submit': 'സമർപ്പിക്കുക',
      'Delete': 'ഇല്ലാതാക്കുക',
      'Edit': 'എഡിറ്റ് ചെയ്യുക',
      'View': 'കാണുക',
      'Search': 'തിരയുക',
      'Filter': 'ഫിൽട്ടർ',
      'Refresh': 'റിഫ്രഷ് ചെയ്യുക',
      'Try Again': 'വീണ്ടും ശ്രമിക്കുക',
      'Retry': 'വീണ്ടും ശ്രമിക്കുക',
      'No data available': 'ഡാറ്റ ലഭ്യമല്ല',
      'Failed to load': 'ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു',
      'Please try again': 'ദയവായി വീണ്ടും ശ്രമിക്കുക',
      'An error occurred': 'ഒരു പിശക് സംഭവിച്ചു',
      'Loading': 'ലോഡ് ചെയ്യുന്നു',
      'Updating': 'അപ്ഡേറ്റ് ചെയ്യുന്നു'
    },
    'kn': {
      // Price Forecast Page
      'Price Trend': 'ಬೆಲೆ ಪ್ರವೃತ್ತಿ',
      'Market Analysis': 'ಮಾರುಕಟ್ಟೆ ವಿಶ್ಲೇಷಣೆ',
      'Current Price': 'ಪ್ರಸ್ತುತ ಬೆಲೆ',
      '30-Day Forecast': '30-ದಿನ ಮುನ್ಸೂಚನೆ',
      'Confidence Level': 'ವಿಶ್ವಾಸ ಮಟ್ಟ',
      'Time Range': 'ಸಮಯ ಶ್ರೇಣಿ',
      'Year': 'ವರ್ಷ',
      'Quick Filters': 'ತ್ವರಿತ ಫಿಲ್ಟರ್‌ಗಳು',
      'This Week': 'ಈ ವಾರ',
      'This Month': 'ಈ ತಿಂಗಳು',
      'This Quarter': 'ಈ ತ್ರೈಮಾಸಿಕ',
      'No Crops to Forecast': 'ಮುನ್ಸೂಚನೆಗೆ ಬೆಳೆಗಳಿಲ್ಲ',
      'Add crops in Account Centre to see price predictions': 'ಬೆಲೆ ಮುನ್ಸೂಚನೆಗಳನ್ನು ನೋಡಲು ಖಾತೆ ಕೇಂದ್ರದಲ್ಲಿ ಬೆಳೆಗಳನ್ನು ಸೇರಿಸಿ',
      'per kg': 'ಪ್ರತಿ ಕಿಲೋ',
      'Filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
      'Advanced Filters': 'ಸುಧಾರಿತ ಫಿಲ್ಟರ್‌ಗಳು',
      '7 Days': '7 ದಿನಗಳು',
      '15 Days': '15 ದಿನಗಳು',
      '30 Days': '30 ದಿನಗಳು',
      '60 Days': '60 ದಿನಗಳು',
      '90 Days': '90 ದಿನಗಳು',
      
      // Updates Page
      'Updates': 'ಅಪ್‌ಡೇಟ್‌ಗಳು',
      'Your notifications': 'ನಿಮ್ಮ ಅಧಿಸೂಚನೆಗಳು',
      'No Updates Yet': 'ಇನ್ನೂ ಅಪ್‌ಡೇಟ್‌ಗಳಿಲ್ಲ',
      'You\'ll see notifications here when there are updates': 'ಅಪ್‌ಡೇಟ್‌ಗಳು ಇದ್ದಾಗ ನೀವು ಇಲ್ಲಿ ಅಧಿಸೂಚನೆಗಳನ್ನು ನೋಡುತ್ತೀರಿ',
      'Bid Completed - Winner Declared!': 'ಬಿಡ್ ಪೂರ್ಣಗೊಂಡಿತು - ವಿಜೇತ ಘೋಷಿಸಲಾಗಿದೆ!',
      'Profile Changes Approved': 'ಪ್ರೊಫೈಲ್ ಬದಲಾವಣೆಗಳನ್ನು ಅನುಮೋದಿಸಲಾಗಿದೆ',
      'New Connection Request': 'ಹೊಸ ಸಂಪರ್ಕ ವಿನಂತಿ',
      'Transport Update': 'ಸಾರಿಗೆ ಅಪ್‌ಡೇಟ್',
      
      // Weather Page - Comprehensive translations
      'Pest & Disease Risk': 'ಕೀಟ ಮತ್ತು ರೋಗ ಅಪಾಯ',
      'Fungal Disease Risk': 'ಶಿಲೀಂಧ್ರ ರೋಗ ಅಪಾಯ',
      'Apply fungicide if needed': 'ಅಗತ್ಯವಿದ್ದರೆ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ',
      'Monitor crops closely': 'ಬೆಳೆಗಳನ್ನು ನಿಕಟವಾಗಿ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ',
      'Conditions unfavorable for diseases': 'ರೋಗಗಳಿಗೆ ಪ್ರತಿಕೂಲ ಪರಿಸ್ಥಿತಿಗಳು',
      'Pest Activity Level': 'ಕೀಟ ಚಟುವಟಿಕೆ ಮಟ್ಟ',
      'Normal pest activity expected': 'ಸಾಮಾನ್ಯ ಕೀಟ ಚಟುವಟಿಕೆ ನಿರೀಕ್ಷಿತ',
      'Warm humid conditions favor pests': 'ಬೆಚ್ಚಗಿನ ಆರ್ದ್ರ ಪರಿಸ್ಥಿತಿಗಳು ಕೀಟಗಳಿಗೆ ಅನುಕೂಲ',
      'Cool conditions reduce pest activity': 'ತಂಪಾದ ಪರಿಸ್ಥಿತಿಗಳು ಕೀಟ ಚಟುವಟಿಕೆಯನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತವೆ',
      'Moon & Astronomy': 'ಚಂದ್ರ ಮತ್ತು ಖಗೋಳಶಾಸ್ತ್ರ',
      'New Moon': 'ಅಮಾವಾಸ್ಯೆ',
      'Moonrise': 'ಚಂದ್ರೋದಯ',
      'Moonset': 'ಚಂದ್ರಾಸ್ತ',
      'Dew Point': 'ಇಬ್ಬನಿ ಬಿಂದು',
      'Temperature Range': 'ತಾಪಮಾನ ಶ್ರೇಣಿ',
      'Auto-Refresh': 'ಸ್ವಯಂ-ರಿಫ್ರೆಶ್',
      'Last': 'ಕೊನೆಯ',
      'Next refresh': 'ಮುಂದಿನ ರಿಫ್ರೆಶ್',
      'High': 'ಹೆಚ್ಚು',
      'Moderate': 'ಮಧ್ಯಮ',
      'Low': 'ಕಡಿಮೆ',
      'Current': 'ಪ್ರಸ್ತುತ',
      'Min': 'ಕನಿಷ್ಠ',
      'Max': 'ಗರಿಷ್ಠ',
      'Live Weather Data': 'ನೇರ ಹವಾಮಾನ ಡೇಟಾ',
      'Simulated Data': 'ಸಿಮ್ಯುಲೇಟೆಡ್ ಡೇಟಾ',
      'Updated': 'ಅಪ್‌ಡೇಟ್ ಮಾಡಲಾಗಿದೆ',
      'Hourly': 'ಗಂಟೆಗೆ',
      'Five Day': '5-ದಿನ',
      'Now': 'ಈಗ',
      'Today': 'ಇಂದು',
      'Wind': 'ಗಾಳಿ',
      'Humidity': 'ಆರ್ದ್ರತೆ',
      'Visibility': 'ಗೋಚರತೆ',
      'Pressure': 'ಒತ್ತಡ',
      'Sunrise': 'ಸೂರ್ಯೋದಯ',
      'Sunset': 'ಸೂರ್ಯಾಸ್ತ',
      'Farming Advice': 'ಕೃಷಿ ಸಲಹೆ',
      'Crop Conditions': 'ಬೆಳೆ ಪರಿಸ್ಥಿತಿಗಳು',
      'Soil Moisture': 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
      'UV Index': 'UV ಸೂಚ್ಯಂಕ',
      'Feels Like': 'ಅನುಭವ',
      'Rain Chance': 'ಮಳೆ ಸಾಧ್ಯತೆ',
      'Best Times Today': 'ಇಂದಿನ ಅತ್ಯುತ್ತಮ ಸಮಯಗಳು',
      'Irrigation': 'ನೀರಾವರಿ',
      'Harvesting': 'ಕೊಯ್ಲು',
      'Spraying': 'ಸಿಂಪಣೆ',
      'Field Work': 'ಹೊಲದ ಕೆಲಸ',
      'Transplanting': 'ನಾಟಿ',
      'Not Recommended': 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿಲ್ಲ',
      'Ideal Conditions': 'ಆದರ್ಶ ಪರಿಸ್ಥಿತಿಗಳು',
      'Evening Preferred': 'ಸಂಜೆ ಆದ್ಯತೆ',
      'Air Quality Index': 'ವಾಯು ಗುಣಮಟ್ಟ ಸೂಚ್ಯಂಕ',
      'Overall AQI': 'ಒಟ್ಟಾರೆ AQI',
      'Good': 'ಒಳ್ಳೆಯದು',
      'Unhealthy': 'ಅನಾರೋಗ್ಯಕರ',
      'Very Unhealthy': 'ಬಹಳ ಅನಾರೋಗ್ಯಕರ',
      'No Rain Expected': 'ಮಳೆ ನಿರೀಕ್ಷಿಸಲಾಗಿಲ್ಲ',
      'Rain Expected': 'ಮಳೆ ನಿರೀಕ್ಷಿತ',
      'Today\'s Agriculture Summary': 'ಇಂದಿನ ಕೃಷಿ ಸಾರಾಂಶ',
      'Avg Temperature': 'ಸರಾಸರಿ ತಾಪಮಾನ',
      'Max Wind': 'ಗರಿಷ್ಠ ಗಾಳಿ',
      'Total Precipitation': 'ಒಟ್ಟು ಮಳೆ',
      'Avg Humidity': 'ಸರಾಸರಿ ಆರ್ದ್ರತೆ',
      'Next 6 Hours (Live)': 'ಮುಂದಿನ 6 ಗಂಟೆಗಳು (ನೇರ)',
      'Weather Alerts': 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು',
      
      // Crop names
      'Rice': 'ಅಕ್ಕಿ',
      'Wheat': 'ಗೋಧಿ',
      'Coffee': 'ಕಾಫಿ',
      'Corn': 'ಜೋಳ',
      'Cotton': 'ಹತ್ತಿ',
      'Sugarcane': 'ಕಬ್ಬು',
      'Tomato': 'ಟೊಮೇಟೊ',
      'Onion': 'ಈರುಳ್ಳಿ',
      'Potato': 'ಆಲೂಗಡ್ಡೆ',
      'Chili': 'ಮೆಣಸಿನಕಾಯಿ',
      
      // Dashboard and UI elements
      'Leaderboard': 'ಲೀಡರ್‌ಬೋರ್ಡ್',
      'Top performers': 'ಉತ್ತಮ ಪ್ರದರ್ಶಕರು',
      'No sales data yet': 'ಇನ್ನೂ ಮಾರಾಟ ಡೇಟಾ ಇಲ್ಲ',
      'Track your crops': 'ನಿಮ್ಮ ಬೆಳೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      'Unable to fetch live data for rice. Showing estimated prices based on typical market rates.': 'ಅಕ್ಕಿಗೆ ನೇರ ಡೇಟಾವನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಸಾಮಾನ್ಯ ಮಾರುಕಟ್ಟೆ ದರಗಳ ಆಧಾರದ ಮೇಲೆ ಅಂದಾಜು ಬೆಲೆಗಳನ್ನು ತೋರಿಸುತ್ತಿದೆ.',
      'Unable to fetch live data': 'ನೇರ ಡೇಟಾವನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
      'Showing estimated prices based on typical market rates': 'ಸಾಮಾನ್ಯ ಮಾರುಕಟ್ಟೆ ದರಗಳ ಆಧಾರದ ಮೇಲೆ ಅಂದಾಜು ಬೆಲೆಗಳನ್ನು ತೋರಿಸುತ್ತಿದೆ',
      
      // Weather conditions
      'Mist': 'ಮಂಜು',
      'Fog': 'ಮಂಜು',
      'Haze': 'ಮಂಜು',
      'Drizzle': 'ಚಿಮುಕಿಸುವ ಮಳೆ',
      'Showers': 'ಮಳೆ',
      'Thunderstorm': 'ಗುಡುಗು ಸಹಿತ ಮಳೆ',
      'Snow': 'ಹಿಮ',
      'Sleet': 'ಹಿಮ ಮಳೆ',
      'Partly Cloudy': 'ಭಾಗಶಃ ಮೇಘಾವೃತ',
      'Mostly Cloudy': 'ಹೆಚ್ಚಾಗಿ ಮೇಘಾವೃತ',
      'Overcast': 'ಸಂಪೂರ್ಣ ಮೇಘಾವೃತ',
      'Clear Sky': 'ಸ್ಪಷ್ಟ ಆಕಾಶ',
      'Fair': 'ಒಳ್ಳೆಯ ಹವಾಮಾನ',
      
      // Common words
      'Home': 'ಮುಖ್ಯಪುಟ',
      'Back': 'ಹಿಂದೆ',
      'Loading...': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'Error': 'ದೋಷ',
      'Success': 'ಯಶಸ್ಸು',
      'Warning': 'ಎಚ್ಚರಿಕೆ',
      'Information': 'ಮಾಹಿತಿ',
      'Close': 'ಮುಚ್ಚಿ',
      'Save': 'ಉಳಿಸಿ',
      'Cancel': 'ರದ್ದುಮಾಡಿ',
      'Submit': 'ಸಲ್ಲಿಸಿ',
      'Delete': 'ಅಳಿಸಿ',
      'Edit': 'ಸಂಪಾದಿಸಿ',
      'View': 'ನೋಡಿ',
      'Search': 'ಹುಡುಕಿ',
      'Filter': 'ಫಿಲ್ಟರ್',
      'Refresh': 'ರಿಫ್ರೆಶ್ ಮಾಡಿ',
      'Try Again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'Retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'No data available': 'ಯಾವುದೇ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ',
      'Failed to load': 'ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ',
      'Please try again': 'ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'An error occurred': 'ದೋಷ ಸಂಭವಿಸಿದೆ',
      'Loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ',
      'Updating': 'ಅಪ್‌ಡೇಟ್ ಆಗುತ್ತಿದೆ'
    }
  };

  // Return mock translation if available
  if (mockTranslations[targetLanguage] && mockTranslations[targetLanguage][text]) {
    return mockTranslations[targetLanguage][text];
  }

  // Return original text if no translation available
  return text;
};

// Single text translation
router.post('/', async (req, res) => {
  try {
    const { text, targetLanguage, sourceLanguage = 'en' } = req.body;

    if (!text || !targetLanguage) {
      return res.status(400).json({
        success: false,
        error: 'Text and target language are required'
      });
    }

    const translatedText = await translateWithGoogle(text, targetLanguage, sourceLanguage);

    res.json({
      success: true,
      translatedText,
      sourceLanguage,
      targetLanguage
    });
  } catch (error) {
    console.error('Translation error:', error);
    res.status(500).json({
      success: false,
      error: 'Translation failed',
      translatedText: req.body.text // Return original text on error
    });
  }
});

// Batch translation
router.post('/batch', async (req, res) => {
  try {
    const { texts, targetLanguage, sourceLanguage = 'en' } = req.body;

    if (!Array.isArray(texts) || !targetLanguage) {
      return res.status(400).json({
        success: false,
        error: 'Texts array and target language are required'
      });
    }

    const translatedTexts = await Promise.all(
      texts.map(text => translateWithGoogle(text, targetLanguage, sourceLanguage))
    );

    res.json({
      success: true,
      translatedTexts,
      sourceLanguage,
      targetLanguage
    });
  } catch (error) {
    console.error('Batch translation error:', error);
    res.status(500).json({
      success: false,
      error: 'Batch translation failed',
      translatedTexts: req.body.texts // Return original texts on error
    });
  }
});

// Get supported languages
router.get('/languages', (req, res) => {
  res.json({
    success: true,
    languages: {
      'en': 'English',
      'hi': 'Hindi',
      'te': 'Telugu',
      'ta': 'Tamil',
      'ml': 'Malayalam',
      'kn': 'Kannada'
    }
  });
});

module.exports = router;